// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var accessToken, api, apiVersion, app, assert, chai, ranks, should, supertest, userId;



  supertest = require('supertest');

  chai = require('chai');

  should = chai.should();

  assert = chai.assert;

  app = require('../app').app;

  api = supertest(app);

  apiVersion = app.version;

  userId = 53;

  accessToken = "user_d06dbc5cf2449cec33ff2aad1c4c9632";

  ranks = [18, 19, 20];

  describe('Rank', function() {
    var rankId;
    rankId = null;
    return it('should return 201 when creating new rank', function(done) {
      return api.post("" + apiVersion + "/user/" + userId + "/ranking").send({
        name: "TEST_ranking",
        ranks: ranks
      }).set('x-access-token', accessToken).expect(201).end(function(err, res) {
        var response;
        console.log(res.text);
        response = JSON.parse(res.text);
        console.log(response);
        return done();
      });
    });
  });

}).call(this);
