// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var Attribute, Collection, Constants, Cypher, CypherBuilder, CypherLinkUtil, Entity, EntityUtil, ErrorDevMessage, Logger, Neo, Permission, Rank, RedisKey, Response, Security, Tag, User, basicAuthentication, hasPermission, iced, redis, __iced_k, __iced_k_noop, _create, _delete, _edit, _show, _showDetail, _und;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  _und = require('underscore');

  redis = require('../models/setup').db.redis;

  Logger = require('../util/logger');

  Neo = require('../models/neo');

  User = require('../models/user');

  Entity = require('../models/entity');

  Attribute = require('../models/attribute');

  Tag = require('../models/tag');

  Collection = require('../models/collection');

  Rank = require('../models/rank');

  Permission = require('./permission');

  Constants = require('../config').Constants;

  RedisKey = require('../config').RedisKey;

  Security = require('../config').Security;

  EntityUtil = require('./entity/util');

  Cypher = require('./util/cypher');

  CypherBuilder = Cypher.CypherBuilder;

  CypherLinkUtil = Cypher.CypherLinkUtil;

  Response = require('./util/response');

  ErrorDevMessage = Response.ErrorDevMessage;

  hasPermission = function(req, res, next, cb) {
    var ErrorResponse, errOther, errUser, isPublic, other, reqWithUser, user, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    ErrorResponse = Response.ErrorResponse(res);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "collection.coffee",
        funcname: "hasPermission"
      });
      User.get(req.params.id, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            errOther = arguments[0];
            return other = arguments[1];
          };
        })(),
        lineno: 33
      }));
      Permission.getUser(req, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            errUser = arguments[0];
            return user = arguments[1];
          };
        })(),
        lineno: 34
      }));
      __iced_deferrals._fulfill();
    })(function() {
      isPublic = req.params.id === "public";
      if (errUser || errOther) {
        return cb(true, ErrorResponse(500, ErrorDevMessage.dbIssue()), null);
      }
      if (!other) {
        return cb(true, ErrorResponse(400, ErrorDevMessage.customMsg("User does not exist")), null);
      }
      if (isPublic) {
        reqWithUser = _und.extend(_und.clone(req), {
          user: other
        });
      } else {
        reqWithUser = _und.extend(_und.clone(req), {
          user: user
        });
      }
      if (isPublic || (user && other && other._node.id === user._node.id)) {
        return cb(false, null, reqWithUser);
      }
      return cb(true, ErrorResponse(401, ErrorDevMessage.permissionIssue()), null);
    });
  };

  basicAuthentication = Permission.authCurry(hasPermission);

  _create = function(req, res, next) {
    var collection, entities, entity, err, errs, id, ind, links, ok, publicUser, rank, relationType, sCollection, shareToken, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    if (!req.body.name || !req.body.collection || !req.body.collectionType) {
      return Response.ErrorResponse(res)(400, ErrorDevMessage.missingParam("name, collection, and collectType is required."));
    }
    req.body.createdBy = req.user.serialize().username;
    req.body.user = req.user;
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "collection.coffee",
        funcname: "_create"
      });
      Collection.create(req.body, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return collection = arguments[1];
          };
        })(),
        lineno: 74
      }));
      __iced_deferrals._fulfill();
    })(function() {
      CypherLinkUtil.getOrCreateLink(Rank, req.user._node, collection._node, Constants.REL_COLLECTION, {}, function(err, rel) {});
      errs = [];
      entities = [];
      (function(__iced_k) {
        var _i, _len, _ref;
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "collection.coffee",
          funcname: "_create"
        });
        _ref = collection._node.data.collection;
        for (ind = _i = 0, _len = _ref.length; _i < _len; ind = ++_i) {
          id = _ref[ind];
          Entity.get(id, __iced_deferrals.defer({
            assign_fn: (function(__slot_1, __slot_2, __slot_3, __slot_4) {
              return function() {
                __slot_1[__slot_2] = arguments[0];
                return __slot_3[__slot_4] = arguments[1];
              };
            })(errs, ind, entities, ind),
            lineno: 87
          }));
        }
        __iced_deferrals._fulfill();
      })(function() {
        errs = [];
        links = [];
        sCollection = collection.serialize();
        (function(__iced_k) {
          var _i, _len;
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "collection.coffee",
            funcname: "_create"
          });
          for (rank = _i = 0, _len = entities.length; _i < _len; rank = ++_i) {
            entity = entities[rank];
            if (sCollection.collectionType === "ranking") {
              relationType = Constants.REL_RANK;
            } else {
              relationType = Constants.REL_COLLECT;
            }
            CypherLinkUtil.getOrCreateLink(Rank, collection._node, entity._node, relationType, {
              rank: rank + 1,
              collectionName: sCollection.name
            }, __iced_deferrals.defer({
              assign_fn: (function(__slot_1, __slot_2, __slot_3, __slot_4) {
                return function() {
                  __slot_1[__slot_2] = arguments[0];
                  return __slot_3[__slot_4] = arguments[1];
                };
              })(errs, rank, links, rank),
              lineno: 104
            }));
          }
          __iced_deferrals._fulfill();
        })(function() {
          Logger.debug("Finished creating links");
          shareToken = Security.hashids.encrypt(collection._node.id);
          publicUser = null;
          collection._node.data.shareToken = shareToken;
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "collection.coffee",
              funcname: "_create"
            });
            if (!collection._node.data["private"]) {
              User.get("public", __iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    err = arguments[0];
                    return publicUser = arguments[1];
                  };
                })(),
                lineno: 113
              }));
            }
            redis.set(RedisKey.collectionShareToken(sCollection.id), shareToken, __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  err = arguments[0];
                  return ok = arguments[1];
                };
              })(),
              lineno: 117
            }));
            collection.save(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return err = arguments[0];
                };
              })(),
              lineno: 119
            }));
            __iced_deferrals._fulfill();
          })(function() {
            return Response.OKResponse(res)(201, collection.serialize());
          });
        });
      });
    });
  };

  exports.create = basicAuthentication(_create);

  _show = function(req, res, next) {
    var collection, err, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "collection.coffee",
        funcname: "_show"
      });
      Collection.get(req.params.collectionId, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return collection = arguments[1];
          };
        })(),
        lineno: 128
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (err) {
        return Response.ErrorResponse(res)(500, ErrorDevMessage.dbIssue());
      }
      return Response.OKResponse(res)(200, collection.serialize());
    });
  };

  _showDetail = function(req, res, next) {
    var attrBlobs, collection, dataBlobs, entity, entityId, err, ind, sCollection, sEntities, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "collection.coffee",
        funcname: "_showDetail"
      });
      Collection.get(req.params.collectionId, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return collection = arguments[1];
          };
        })(),
        lineno: 134
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (err) {
        return Response.ErrorResponse(res)(500, ErrorDevMessage.dbIssue());
      }
      attrBlobs = [];
      dataBlobs = [];
      sEntities = [];
      sCollection = collection.serialize();
      (function(__iced_k) {
        var _i, _len, _ref;
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "collection.coffee",
          funcname: "_showDetail"
        });
        _ref = sCollection.collection;
        for (ind = _i = 0, _len = _ref.length; _i < _len; ind = ++_i) {
          entityId = _ref[ind];
          Entity.get(entityId, __iced_deferrals.defer({
            assign_fn: (function(__slot_1, __slot_2) {
              return function() {
                err = arguments[0];
                return __slot_1[__slot_2] = arguments[1];
              };
            })(sEntities, ind),
            lineno: 144
          }));
        }
        __iced_deferrals._fulfill();
      })(function() {
        (function(__iced_k) {
          var _i, _len;
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "collection.coffee",
            funcname: "_showDetail"
          });
          for (ind = _i = 0, _len = sEntities.length; _i < _len; ind = ++_i) {
            entity = sEntities[ind];
            EntityUtil.getEntityAttributes(entity, __iced_deferrals.defer({
              assign_fn: (function(__slot_1, __slot_2) {
                return function() {
                  return __slot_1[__slot_2] = arguments[0];
                };
              })(attrBlobs, ind),
              lineno: 148
            }));
            EntityUtil.getEntityData(entity, __iced_deferrals.defer({
              assign_fn: (function(__slot_1, __slot_2) {
                return function() {
                  return __slot_1[__slot_2] = arguments[0];
                };
              })(dataBlobs, ind),
              lineno: 149
            }));
          }
          __iced_deferrals._fulfill();
        })(function() {
          var _i, _len;
          for (ind = _i = 0, _len = sEntities.length; _i < _len; ind = ++_i) {
            entity = sEntities[ind];
            sEntities[ind] = entity.serialize(null, {
              attributes: attrBlobs[ind],
              data: dataBlobs[ind]
            });
          }
          sCollection.collectionDetails = sEntities;
          return Response.OKResponse(res)(200, sCollection);
        });
      });
    });
  };

  exports.show = basicAuthentication(_show);

  _edit = function(req, res, next) {
    var collection, entities, entity, entityId, err, errR, errs, ind, newCollection, newIds, oldCollection, rankMap, rel, relationType, rels, removedIds, updateRankIds, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    if (!req.body.name || !req.body.collection) {
      return Response.ErrorResponse(res)(400, ErrorDevMessage.missingParam("name or collection"));
    }
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "collection.coffee",
        funcname: "_edit"
      });
      Collection.get(req.params.collectionId, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            errR = arguments[0];
            return collection = arguments[1];
          };
        })(),
        lineno: 166
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (errR) {
        return Response.ErrorResponse(res)(400, errR);
      }
      oldCollection = _und.clone(collection.serialize());
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "collection.coffee",
          funcname: "_edit"
        });
        Collection.put(req.params.collection, req.body, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              errR = arguments[0];
              return collection = arguments[1];
            };
          })(),
          lineno: 171
        }));
        __iced_deferrals._fulfill();
      })(function() {
        var _i, _ref, _results;
        if (errR) {
          return Response.ErrorResponse(res)(400, errR);
        }
        newCollection = _und.clone(collection.serialize());
        Logger.debug("Old Collection: " + oldCollection);
        Logger.debug("New Collection: " + newCollection);
        rankMap = _und.object(newCollection.collection, (function() {
          _results = [];
          for (var _i = 1, _ref = newCollection.collection.length; 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
          return _results;
        }).apply(this));
        Logger.debug("RankMap: " + rankMap);
        removedIds = _und.difference(oldCollection.collection, newCollection.collection);
        Logger.debug("To Remove " + removedIds);
        entities = [];
        if (oldCollection.collectionType === "ranking") {
          relationType = Constants.REL_RANK;
        } else {
          relationType = Constants.REL_COLLECT;
        }
        (function(__iced_k) {
          var _j, _len;
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "collection.coffee",
            funcname: "_edit"
          });
          for (ind = _j = 0, _len = removedIds.length; _j < _len; ind = ++_j) {
            entityId = removedIds[ind];
            Entity.get(entityId, __iced_deferrals.defer({
              assign_fn: (function(__slot_1, __slot_2) {
                return function() {
                  err = arguments[0];
                  return __slot_1[__slot_2] = arguments[1];
                };
              })(entities, ind),
              lineno: 195
            }));
          }
          __iced_deferrals._fulfill();
        })(function() {
          (function(__iced_k) {
            var _j, _len;
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "collection.coffee",
              funcname: "_edit"
            });
            for (ind = _j = 0, _len = entities.length; _j < _len; ind = ++_j) {
              entity = entities[ind];
              CypherLinkUtil.deleteLink(Rank, collection._node, entity._node, relationType);
            }
            __iced_deferrals._fulfill();
          })(function() {
            newIds = _und.difference(newCollection.collection, oldCollection.collection);
            Logger.debug("To Add " + newIds);
            entities = [];
            (function(__iced_k) {
              var _j, _len;
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "collection.coffee",
                funcname: "_edit"
              });
              for (ind = _j = 0, _len = newIds.length; _j < _len; ind = ++_j) {
                entityId = newIds[ind];
                Entity.get(entityId, __iced_deferrals.defer({
                  assign_fn: (function(__slot_1, __slot_2) {
                    return function() {
                      err = arguments[0];
                      return __slot_1[__slot_2] = arguments[1];
                    };
                  })(entities, ind),
                  lineno: 208
                }));
              }
              __iced_deferrals._fulfill();
            })(function() {
              (function(__iced_k) {
                var _j, _len;
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "collection.coffee",
                  funcname: "_edit"
                });
                for (ind = _j = 0, _len = entities.length; _j < _len; ind = ++_j) {
                  entity = entities[ind];
                  CypherLinkUtil.getOrCreateLink(Rank, collection._node, entity._node, relationType, {
                    rank: rankMap[entity._node.id.toString()],
                    collectionName: newCollection.name
                  }, function(err, rel) {});
                }
                __iced_deferrals._fulfill();
              })(function() {
                updateRankIds = _und.intersection(newCollection.collection, oldCollection.collection);
                Logger.debug("To Update " + updateRankIds);
                entities = [];
                (function(__iced_k) {
                  var _j, _len;
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "collection.coffee",
                    funcname: "_edit"
                  });
                  for (ind = _j = 0, _len = updateRankIds.length; _j < _len; ind = ++_j) {
                    entityId = updateRankIds[ind];
                    Entity.get(entityId, __iced_deferrals.defer({
                      assign_fn: (function(__slot_1, __slot_2) {
                        return function() {
                          err = arguments[0];
                          return __slot_1[__slot_2] = arguments[1];
                        };
                      })(entities, ind),
                      lineno: 224
                    }));
                  }
                  __iced_deferrals._fulfill();
                })(function() {
                  errs = [];
                  rels = [];
                  (function(__iced_k) {
                    var _j, _len;
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "collection.coffee",
                      funcname: "_edit"
                    });
                    for (ind = _j = 0, _len = entities.length; _j < _len; ind = ++_j) {
                      entity = entities[ind];
                      Logger.debug("for entity " + entity._node.id + "@" + rankMap[entity._node.id.toString()]);
                      CypherLinkUtil.updateLink(Rank, collection._node, entity._node, Constants.REL_RANK, {
                        rank: rankMap[entity._node.id.toString()],
                        collectionName: newCollection.name
                      }, __iced_deferrals.defer({
                        assign_fn: (function() {
                          return function() {
                            err = arguments[0];
                            return rel = arguments[1];
                          };
                        })(),
                        lineno: 234
                      }));
                    }
                    __iced_deferrals._fulfill();
                  })(function() {
                    err = _und.find(errs, function(err) {
                      return err;
                    });
                    if (err) {
                      return cb(true, ErrorResponse(500, ErrorDevMessage.dbIssue()), null);
                    }
                    return Response.OKResponse(res)(200, {});
                  });
                });
              });
            });
          });
        });
      });
    });
  };

  exports.edit = basicAuthentication(_edit);

  _delete = function(req, res, next) {
    return res.status(503).json({
      error: "Not Implemented"
    });
  };

  exports["delete"] = basicAuthentication(_delete);

  exports.shareView = function(req, res, next) {
    var collectionId;
    collectionId = Security.hashids.decrypt(req.params.shareToken);
    if (parseInt(collectionId)) {
      req.params.collectionId = collectionId;
      return _showDetail(req, res, next);
    } else {
      return Response.ErrorResponse(res)(404, ErrorDevMessage.notFound());
    }
  };

}).call(this);
