// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var NumUtil, RedisKey, redis, resolveSlug, slug;



  slug = require('slug');

  redis = require('../models/setup').db.redis;

  NumUtil = require('../util/numUtil');

  RedisKey = require('../config').RedisKey;

  exports.resolveSlug = resolveSlug = function(slug, cb) {
    if (NumUtil.isNum(slug)) {
      return cb(null, slug);
    } else {
      return redis.hget(RedisKey.slugToId, slug, cb);
    }
  };

  exports.slugify = function(title) {
    return slug(title);
  };

}).call(this);
