// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var Entity;



  Entity = require('../models/entity');

  exports.create = function(req, res, next) {
    var data;
    data = {
      name: req.body['name']
    };
    return Entity.create(data, function(err, entity) {
      if (err) {
        return next(err);
      }
      return res.json(entity);
    });
  };

  exports.show = function(req, res, next) {
    return Entity.get(req.params.id, function(err, entity) {
      if (err) {
        return next(err);
      }
      return res.json(entity);
    });
  };

  exports.edit = function(req, res, next) {
    return Entity.get(req.params.id, function(err, entity) {
      if (err) {
        return next(err);
      }
      return res.json(entity);
    });
  };

  exports.del = function(req, res, next) {
    return Entity.get(req.params.id, function(err, entity) {
      if (err) {
        return next(err);
      }
      return entity.del(function(err) {
        if (err) {
          return next(err);
        }
        return res.json({});
      });
    });
  };

  /*
      Connect another entity to current one using [relation]
      DATA : {
          action: add/rm
          other: entityId,
      }
  */


  /*
      List all entity related to this entity through [relation]
  */


}).call(this);
