// Generated by IcedCoffeeScript 1.6.3-e

/*
# Responsible for parsing query parameters
*/

(function() {
  var DEFAULT_CONFIG;



  DEFAULT_CONFIG = {
    fields: ["*"],
    limit: 100,
    offset: 0,
    expand: {}
  };

  exports.parseQuery = function(res) {
    return {
      fields: [],
      expand: {},
      limit: [],
      offset: []
    };
  };

}).call(this);
