// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var Attribute, Constants, Entity, Link, Logger, Neo, Response, StdSchema, Tag, Utility, Vote, rest, _und;



  _und = require('underscore');

  rest = require('restler');

  Logger = require('util');

  Neo = require('../models/neo');

  Entity = require('../models/entity');

  Attribute = require('../models/attribute');

  Tag = require('../models/tag');

  Vote = require('../models/vote');

  Link = require('../models/link');

  StdSchema = require('../models/stdSchema');

  Constants = StdSchema.Constants;

  Response = StdSchema;

  Utility = require('./utility');

  exports.getCreated = function(req, res, next) {};

  exports.getVoted = function(req, res, next) {};

  exports.getCommented = function(req, res, next) {};

}).call(this);
