// Generated by IcedCoffeeScript 1.6.3-e

/*
# Retrieves data from remote source
*/

(function() {
  var rest;



  rest = require('restler');

  exports.getJSONData = function(remoteAddress, cb) {
    if (!remoteAddress) {
      return cb("N/A");
    }
    return rest.get(remoteAddress).on('complete', function(remoteData, remoteRes) {
      if (remoteRes == null) {
        return cb("");
      } else if (remoteRes.headers['content-type'].indexOf('application/json') !== -1) {
        return cb(remoteData);
      } else {
        return cb("N/A");
      }
    });
  };

}).call(this);
