// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var Collection, CollectionSchema, INDEX_NAME, Indexes, Logger, Neo, SchemaUtil, SchemaValidation, Slug, redis, _und,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  _und = require('underscore');

  Logger = require('../util/logger');

  Slug = require('../util/slug');

  Neo = require('./neo');

  redis = require('./setup').db.redis;

  SchemaUtil = require('./stdSchema');

  INDEX_NAME = 'nCollection';

  Indexes = [
    {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'name',
      INDEX_VALUE: ''
    }
  ];

  CollectionSchema = {
    createdBy: 'username',
    "private": true,
    name: 'New Collection',
    collection: [-1],
    shareToken: '',
    description: '',
    collectionType: 'list'
  };

  SchemaValidation = {};

  module.exports = Collection = (function(_super) {
    __extends(Collection, _super);

    function Collection(_node) {
      this._node = _node;
      Collection.__super__.constructor.call(this, this._node);
    }

    return Collection;

  })(Neo);


  /*
  Static Method
  */

  Collection.Name = 'nCollection';

  Collection.INDEX_NAME = INDEX_NAME;

  Collection.Indexes = Indexes;

  Collection.validateSchema = function(data) {
    return SchemaUtil.validate(SchemaValidation, data);
  };

  Collection.getSlugTitle = function(data) {
    return Slug.slugify(data.name);
  };

  Collection.deserialize = function(data) {
    return Neo.deserialize(CollectionSchema, data);
  };

  Collection.create = function(reqBody, cb) {
    return Neo.create(Collection, reqBody, Indexes, cb);
  };

  Collection.get = function(id, cb) {
    return Neo.get(Collection, id, cb);
  };

  Collection.getOrCreate = function(reqBody, cb) {
    Logger.debug("Collection getOrCreate");
    return Neo.getOrCreate(Collection, reqBody, cb);
  };

  Collection.put = function(nodeId, reqBody, cb) {
    return Neo.put(Collection, nodeId, reqBody, cb);
  };

}).call(this);
