// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var CommentSchema, Logger, Neo, SchemaUtil, SchemaValidation, Setup, _und;



  _und = require('underscore');

  Logger = require('util');

  Setup = require('./setup');

  Neo = require('./neo');

  SchemaUtil = require('./stdSchema');

  CommentSchema = {
    comment: '',
    username: '',
    location: ''
  };

  SchemaValidation = {
    comment: SchemaUtil.required('string')
  };

  module.exports = {
    validateSchema: function(data) {
      return SchemaUtil.validate(SchemaValidation, data);
    },
    deserialize: function(data) {
      return Neo.deserialize(CommentSchema, data);
    },
    fillMetaData: function(data) {
      return Neo.fillMetaData(data);
    }
  };

}).call(this);
