// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var Composed, Logger, RedisModel, SchemaUtil, Setup, _ref, _und,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };



  _und = require('underscore');

  Logger = require('util');

  Setup = require('./setup');

  RedisModel = require('./redisModel');

  SchemaUtil = require('./stdSchema');

  module.exports = Composed = (function(_super) {
    __extends(Composed, _super);

    function Composed() {
      _ref = Composed.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Composed.Name = "composed";

    Composed.Schema = {
      title: '',
      profileIconUrl: '',
      authorName: [],
      authorProfileUrl: [],
      hashTag: [],
      dataChain: [],
      entityId: []
    };

    return Composed;

  })(RedisModel);

}).call(this);
