// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var Entity, EntitySchema, INDEX_NAME, Indexes, Neo, Setup, iced, redis, __iced_k, __iced_k_noop, _und,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  _und = require('underscore');

  Setup = require('./setup');

  Neo = require('./neo');

  redis = Setup.db.redis;

  INDEX_NAME = 'nEntity';

  Indexes = [
    {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'name',
      INDEX_VALUE: ''
    }, {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'description',
      INDEX_VALUE: ''
    }, {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'description',
      INDEX_VALUE: ''
    }
  ];

  EntitySchema = {
    imgURL: '',
    name: 'Name of entity',
    description: '',
    type: '',
    tags: ['']
  };

  module.exports = Entity = (function(_super) {
    __extends(Entity, _super);

    function Entity(_node) {
      this._node = _node;
      Entity.__super__.constructor.call(this, this._node);
    }

    Entity.prototype.vote = function(attr, voteLink, cb) {
      var downVote, err, rel, upVote, voteTally, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "entity.coffee",
          funcname: "Entity.vote"
        });
        _this._node.createRelationshipTo(attr._node, voteLink.name, voteLink.data, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              err = arguments[0];
              return rel = arguments[1];
            };
          })(),
          lineno: 45
        }));
        __iced_deferrals._fulfill();
      })(function() {
        if (err) {
          return cb(err);
        }
        redis.incr("entity:" + _this._node.id + "::attr:" + attr._node.id + "::" + voteLink.data.type);
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "entity.coffee",
            funcname: "Entity.vote"
          });
          redis.get("entity:" + _this._node.id + "::attr:" + attr._node.id + "::positive", __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return upVote = arguments[1];
              };
            })(),
            lineno: 51
          }));
          __iced_deferrals._fulfill();
        })(function() {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "entity.coffee",
              funcname: "Entity.vote"
            });
            redis.get("entity:" + _this._node.id + "::attr:" + attr._node.id + "::negative", __iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  err = arguments[0];
                  return downVote = arguments[1];
                };
              })(),
              lineno: 52
            }));
            __iced_deferrals._fulfill();
          })(function() {
            voteTally = {
              upVote: parseInt(upVote) || 0,
              downVote: parseInt(downVote) || 0
            };
            return cb(null, voteTally);
          });
        });
      });
    };

    Entity.prototype.unlinkEntity = function(other, relation, cb) {
      return this._node.getRelationships(relation, function(err, rels) {
        var i, reToOther, rel, _i, _j, _len, _len1, _results;
        if (err) {
          return cb(err);
        }
        reToOther = [];
        for (i = _i = 0, _len = rels.length; _i < _len; i = ++_i) {
          rel = rels[i];
          if (rel.end === other) {
            reToOther.push(rel);
          }
        }
        _results = [];
        for (_j = 0, _len1 = reToOther.length; _j < _len1; _j++) {
          rel = reToOther[_j];
          _results.push((function(rel) {
            return rel.del(function(err) {
              if (err) {
                return cb(err);
              }
            });
          })(rel));
        }
        return _results;
      });
    };

    return Entity;

  })(Neo);

  /*
  Static Method
  */


  Entity.Name = 'nEntity';

  Entity.INDEX_NAME = INDEX_NAME;

  Entity.Indexes = Indexes;

  Entity.deserialize = function(data) {
    return Neo.deserialize(EntitySchema, data);
  };

  Entity.create = function(reqBody, cb) {
    return Neo.create(Entity, reqBody, Indexes, cb);
  };

  Entity.get = function(id, cb) {
    return Neo.get(Entity, id, cb);
  };

  Entity.getOrCreate = function(reqBody, cb) {
    return Neo.getOrCreate(Entity, reqBody, cb);
  };

  Entity.put = function(nodeId, reqBody, cb) {
    return Neo.put(Entity, nodeId, reqBody, cb);
  };

}).call(this);

/*
//@ sourceMappingURL=entity.map
*/
