// Generated by IcedCoffeeScript 1.6.3-e
(function() {
  var Contants, INDEX_NAME, Indexes, Rank, RankSchema, StdSchema, _und;



  _und = require('underscore');

  StdSchema = require('./stdSchema');

  Contants = StdSchema.Contants;

  INDEX_NAME = 'rRank';

  Indexes = [
    {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'rank',
      INDEX_VALUE: ''
    }, {
      INDEX_NAME: INDEX_NAME,
      INDEX_KEY: 'rankingName',
      INDEX_VALUE: ''
    }
  ];

  RankSchema = {
    rank: -1,
    rankingName: 'New Ranking'
  };

  module.exports = Rank = (function() {
    function Rank(voteData) {
      var data;
      this.name = Constants.REL_RANK;
      data = _und.clone(voteData);
      _und.defaults(data, RankSchema);
      _und.pick(data, _und.keys(RankSchema));
      this.data = data;
      if (!this.data.time) {
        this.data.time = '' + new Date().getTime();
      }
    }

    return Rank;

  })();


  /*
  Static Method
  */

  Rank.Name = 'rRank';

  Rank.INDEX_NAME = INDEX_NAME;

}).call(this);
