// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var AttrLink, Constants, ErrorResponse, Link, _und;



  _und = require('underscore');

  exports.Constants = Constants = {
    INDEX_NAME: 'node',
    INDEX_KEY: 'type',
    INDEX_VAL: 'entity',
    REL_LOCATION: '_LOCATION',
    REL_VOTE: '_VOTE',
    REL_AWARD: '_AWARD',
    REL_ATTRIBUTE: '_ATTRIBUTE',
    REL_PARENT: '_PARENT',
    REL_CHILD: '_CHILD',
    REL_CONTAINER: '_CONTAINER',
    REL_RESOURCE: '_RESOURCE',
    REL_META: '_META'
  };

  /*
      Relationship Schema
  */


  exports.ErrorResponse = ErrorResponse = (function() {
    function ErrorResponse(msg, fix) {
      this.msg = msg;
      this.fix = fix;
    }

    ErrorResponse.prototype.serialize = function() {
      return {
        message: this.msg,
        solution: this.fix
      };
    };

    return ErrorResponse;

  })();

  AttrLink = (function() {
    function AttrLink() {}

    return AttrLink;

  })();

  Link = (function() {
    function Link(linkName, linkData) {
      this.linkName = linkName;
      this.linkData = linkData;
    }

    return Link;

  })();

}).call(this);

/*
//@ sourceMappingURL=stdSchema.map
*/
